### ISSUE TITLE
Cannot import into eclipse with the HTTPmsg_CNL113312.tpd file

### ISSUE THREAD

**Issue by yu36yuqing** [eclipse/titan.TestPorts.HTTPmsg#1]
Hi, I am learning the TTCN language, and try to import this project into eclipse.
But I failed to do that and no detail error message from the eclipse.

![image](https://user-images.githubusercontent.com/9708701/29000383-4f44677e-7a9b-11e7-83bf-8e0434fdbd4b.png)

Any advice for this error?
Thanks very much.

**Comment by erititan** [comment]
Hi,

-in general, I'd recommend  you to get familiar with the command line interface before starting to use IDE; compilation errors, if any,  are coming from the core, and not the IDE 
-the error message above says that error log is supposed to give you more info; did you check the error log?

Best regards
Elemer

**Comment by yu36yuqing** [comment]
Thanks for your quick response, the error log is like below:
org.eclipse.titan.common
Error
Sun Aug 06 11:34:54 CST 2017
It was not possible to load the imported project file: 'file:/C:/cygwin64/***/Common_Components/Abstract_Socket_CNL113384/Abstract_Socket_CNL113384.tpd'
imported by: 'file:/C:/cygwin64/***/HTTPmsg/HTTPmsg_CNL113312.tpd'

**Comment by yu36yuqing** [comment]
Hi,
Thanks for your response.
After I check the error log, I found that a dependency project was needed which named "Abstract_Socket_CNL113384.tpd".
With this project, I can import it successfully.
But still failed to compile it with eclipse.

I have installed Cygwin64 in my windows system, how could I do to compile this project with command line as you said?

**Comment by erititan** [comment]
Hi,

-first, make sure all your environment variables are set 
(see https://github.com/eclipse/titan.core/blob/master/README.cygwin)
-if they are, then "compiler -v" will display the compiler version
-create a  separate directory  say "bin" 
-symlink into this directory all files that you want to compile
  ln -s file1 .
  ln -s file2 .
etc.
- "ls -la" will display the created symlinks 
-generate a makefile with "makefilegen *.ttcn *.cc *.hh *.c *.h"  
or "makefilegen ...list of all files ...."
-after the makefile is generated  
compile with "make"

if compilation is successful, then your code is installed and works, so you can move to IDE

Please check also example projects in the forum
https://www.eclipse.org/forums/index.php/f/297/


Best regards 
Elemer

**Comment by yu36yuqing** [comment]
Thanks for your kindly support : )
